apiVersion: v1
kind: Service
metadata:
  name: hello-world-python-service
spec:
  selector:
    app: hwpython
  type: LoadBalancer
  ports:
    - name: hello-world-port
      port: 80
      targetPort: 3333


        